/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MSAStar */

#ifndef _Included_MSAStar
#define _Included_MSAStar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MSAStar
 * Method:    initNativeAStar
 * Signature: (I[I[[FLStericCheck;[[Z[[[ZZZZJJIIID)V
 */
JNIEXPORT void JNICALL Java_MSAStar_initNativeAStar
  (JNIEnv *, jobject, jint, jintArray, jobjectArray, jobject, jobjectArray, jobjectArray, jboolean, jboolean, jboolean, jlong, jlong, jint, jint, jint, jdouble);

/*
 * Class:     MSAStar
 * Method:    doNativeAStar
 * Signature: (ZI[I[ZLStrandRotamers;[[Ljava/lang/String;[I[[IZ[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_MSAStar_doNativeAStar
  (JNIEnv *, jobject, jboolean, jint, jintArray, jbooleanArray, jobject, jobjectArray, jintArray, jobjectArray, jboolean, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
